from turtle import Turtle , Screen

timmy = Turtle()

timmy.color("blue")
timmy.shape("turtle")

timmy.forward(20)
timmy.color("white")
timmy.forward(20)
timmy.color("blue")
timmy.forward(20)
timmy.color("white")
timmy.forward(20)
timmy.color("blue")
timmy.forward(20)
timmy.color("white")
timmy.forward(20)
timmy.color("blue")
timmy.forward(20)
timmy.color("white")
timmy.forward(20)
timmy.color("blue")
timmy.forward(20)
timmy.color("white")
timmy.forward(20)
timmy.color("blue")
timmy.forward(20)
timmy.color("white")
timmy.forward(20)
timmy.color("blue")
timmy.forward(20)
timmy.color("white")
timmy.forward(20)
timmy.color("blue")
timmy.forward(20)

screen = Screen()
screen.exitonclick()